/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.2.2/userguide/multi_project_builds.html
 */

rootProject.name = "apache-pulsar-playground"

pluginManagement {
    // see: https://github.com/ilya40umov/KotLink/blob/master/settings.gradle.kts

    val kotlinVersion = "1.3.61"

    plugins {
        kotlin("jvm") version kotlinVersion
        id("tanvd.kosogor") version "1.0.7"
    }

    resolutionStrategy {
        eachPlugin {
            if(requested.id.id.startsWith("org.jetbrains.kotlin")) {
                useVersion(kotlinVersion)
            }
        }
    }
}


// gradle modules

include("examples:avro")
findProject(":examples:avro")?.name = "avro"
include("examples:quickstart")
findProject(":examples:quickstart")?.name = "quickstart"
include("examples:jsonschema")
findProject(":examples:jsonschema")?.name = "jsonschema"
